Repository Mix-Golem/Client, pull requests merged in 2025-01, with the labels that each got.

#20 Origin/feature/playlist option
  src/components/CreateButton.jsx
  src/components/Follow.jsx
  src/components/LibraryComponent.jsx
  src/components/Playlist.jsx
  src/components/modals/AddSong.jsx
  src/components/modals/RenameMySong.jsx
  src/pages/Create.jsx
  src/pages/Library.jsx
Labels: enhancement

#21 [fix] page move
  package.json
  src/components/Credit.jsx
  src/components/Playlist.jsx
  src/components/SideMenu.jsx
  src/pages/Home.jsx
  src/pages/Social.jsx
  yarn.lock
Labels: duplicate

#22 Origin/feature/login token
  package-lock.json
  src/api/music/AddSongToPlaylist.js
  src/api/music/CreatePlaylist.js
  src/api/music/CreateSong.js
  src/api/music/DeleteMySong.js
  src/api/music/DeletePlaylistByID.js
  src/api/music/DeleteSongInPlaylist.js
  src/api/music/GetAllPlaylist.js
  src/api/music/GetHistory.js
  src/api/music/GetMySong.js
  src/api/music/GetMySongByID.js
  src/api/music/GetPlaylistByID.js
  src/api/music/RenameMySong.js
  src/api/music/RenamePlaylist.js
  src/api/music/SaveSong.js
  src/api/music/TogglePublic.js
  src/api/social/Follow.js
  src/api/social/GetFollowList.js
  src/api/social/Unfollow.js
  src/components/CreateComponent.jsx
  src/components/Credit.jsx
  src/components/LibraryComponent.jsx
  src/components/Playlist.jsx
  src/components/modals/AddSong.jsx
  src/pages/Create.jsx
  src/pages/Library.jsx
  src/pages/Login.jsx
  yarn.lock
Labels: enhancement

#24 [fix] final1
  src/components/Credit.jsx
  src/components/Playlist.jsx
  src/components/TopRank.jsx
  src/pages/Home.jsx
  src/pages/Library.jsx
  src/pages/Social.jsx
Labels: wontfix

#25 Origin/feature/final patch
  src/components/CreateComponent.jsx
  src/components/modals/LoginModal.jsx
  src/pages/Create.jsx
Labels: enhancement

#26 Origin/feature/final patch
  src/components/CreateButton.jsx
  src/components/Lyrics.jsx
  src/components/modals/LoginModal.jsx
  src/pages/Create.jsx
Labels: enhancement
